### ISSUE TITLE
In my first VNC connection, and logged into the system, i am prompted for admin password to set timezone?

### ISSUE THREAD

**Issue by frankyfrank666** [XACCNUS/Cluster#1]
![image](https://user-images.githubusercontent.com/87025076/187508544-6335d16c-4451-48a7-8376-7e00d8289666.png)

**Comment by HongshiTan** [comment]
Hi Frank, may I know your xstartup settings?  we have one guide for the VNC server setup on our cluster: https://xaccnus.github.io/Job-Scheduler/vnc_setup

Let me know if you encounter any problems.

Regards,
Hongshi
