### ISSUE TITLE
HACC@NUS Cluster questions

### ISSUE THREAD

**Issue by YUHSINCHENG1230** [XACCNUS/Cluster#10]
Dear HACC@NUS Team

When i test HACC@NUS Cluster, it has some questions.
1.How can i reset the Cluster to initial state?
2.When i run  srun -p mi210_u280_u55c --pty bash -i  it can't change to  mi210_u280_u55c node
3.I want to run different task in different GPU node, but i found that one of the nodes uses the GPU and the GPU usage on other nodes is also very high. Is it possible to use different nodes for training at the same time?(like picture)
![image (1)](https://github.com/XACCNUS/User-Guide/assets/160841042/daf465f4-b649-48c1-9bd9-58188f734859)
![image (2)](https://github.com/XACCNUS/User-Guide/assets/160841042/f076e750-6013-4169-a6e9-015e527d8f4b)

**Comment by HongshiTan** [comment]
Hi,

May I know what you mean by resetting Cluster to an initial state? 

For your second question: 
you can only run the Slurm command to allocate computing node from hacchead node, in your case you need to exit from your current  Slurm session by executing "exit" to go back to  hacchead node. If you want to allocate multiple node at the same time in the terminal, you can use tmux. 

For your third question:
It suggests that the GPU is used by another user.  You need to check the output of sinfo or squeue, if there is another task running on the node you have been assigned, there would be potential resource conflicts. To exclusively allocate the node, you can specify the maximum number of  CPUs that the node is available, for example:
 
srun -p mi100 --cpus-per-task=128  --pty bash 

It will try to allocate the entire Mi100 node to you, and if there is no enough resources, Slurm will block your allocation until other user's task finished. 

Finally, I would suggest you get familar with Slurm. It is necessary and fundamental to use HACC@NUS efficiently and effectively.

**Comment by YUHSINCHENG1230** [comment]
initial state mean the original environment
example:
when i git clone some project and Installation some kit, and i want to Restore original state, it's like similar to delete.
second question:
I mean i "exit" to go back to hacchead node, and run "srun -p mi210_u280_u55c --pty bash -i" but it not chage to mi210_u280_u55c node
third question:
I mean i use differnt GPU node 
example: run  "srun -p mi25 --pty bash -i" and run "srun -p mi100 --pty bash -i"
but the gpu usage rate is very high even i use only use mi25 but mi100 is not actually used.(mi100  gpu usage rate is very high)

**Comment by HongshiTan** [comment]
Sorry, we don't provide any other user-specific support within the given access right. Specifically, the user needs to be aware of what they have done within the given access resource, and the user has to have a fundamental know of using Linux server. You need to clearly know how to recover or delete the git cloned library and code.  Or we have the right to close your account in case of potential risk to our hardware resources. 

For your second and third questions. Please get familiar with Slurm and tmux, as the account email suggested. Both of them are fundamental tools in HPC and computer science research .

**Comment by HongshiTan** [comment]
As a user, it is crucial that you are fully aware of your actions within the allocated resources. This includes having a fundamental understanding of using a Linux server and being able to manage your work, such as knowing how to recover or delete git cloned libraries and code. We reserve the right to close your account if the users do not have fundamental knowledge and may pose a potential risk to our hardware resources.

Regarding your second and third questions, I strongly recommend familiarizing yourself with Slurm and tmux, as suggested in the account email and demos. These tools are fundamental to HPC and computer science research.

**Comment by YUHSINCHENG1230** [comment]
@HongshiTan 
Sorry, I think you misunderstood my question.
Regarding the first question, I know the Linux server management and git how to use.
Example: When we use Windows for a long time, it may have some problems so we need to reset the system.
I want to know what command can be entered in the command line to reset.

Second question, I think the problem can be simplified to when I want to enter the partition of FPGA, it gets stuck and cannot enter.

For the third question, I want to know if different nodes use the same source.
If not, it would be unreasonable for the GPU usage to be very high.
