### ISSUE TITLE
tmux-sessions-get-killed-on-ssh-logout

### ISSUE THREAD

**Issue by yswntht** [XACCNUS/Cluster#13]
I thought this is a common issue faced with tmux in the initial days of using hacc.

StackExchange suggests a [fix](https://unix.stackexchange.com/questions/659150/tmux-sessions-get-killed-on-ssh-logout) for tmux-sessions-get-killed-on-ssh-logout.

1. start tmux session `systemd-run --scope --user tmux`
2. enable "lingering" within tmux-session `loginctl enable-linger`

These two steps would prevent tmux sessions from being killed.

**Comment by HongshiTan** [comment]
Hi Yswntht,

Thanks. We will add this tip to the hacc_demo repo.

Best regards,
Hongshi
