### ISSUE TITLE
ssh connection failed

### ISSUE THREAD

**Issue by EnXinY** [XACCNUS/Cluster#4]
I try open one terminal and type the following command : ssh my_username@xacchead.d2.comp.nus.edu.sg, i can log in successfully. But    When I close the terminal and log in again, it appears “kex_exchange_identification: read: Connection timed out”. I tried many times and couldn't log in again.

**Comment by EnXinY** [comment]
My username is enxinyi

**Comment by HongshiTan** [comment]
Has been solved
