### ISSUE TITLE
Publickey authentication

### ISSUE THREAD

**Issue by frankyfrank666** [XACCNUS/Cluster#5]
Hi, 

Is it possible to turn on the public key authentication for ssh to allow faster login?

Best

**Comment by HongshiTan** [comment]
Hello! In regards to accessing hacchead, we currently only support password + 2FA access for security reasons. However, we do have a guide available for using VNC to access hacchead. This method only requires you to login once and then you can work as if you were on a cloud. Let me know if you need any further assistance with this.
