### ISSUE TITLE
Can't start vncserver

### ISSUE THREAD

**Issue by bjwtsh** [XACCNUS/Cluster#6]
I'm a contestant of CCFSys-ccc 2023 and want to get the result of my project on VCK5000.
As  I prefer the GUI of vitis ,I follow https://github.com/XACCNUS/Job-Scheduler/vnc_setup.md to deploy VNC server on HACC@NUS.
session:15 was allocated to me in step 0, so I login server with the command: 

ssh -L 5915:localhost:5915 MyUsername@xacchead.d2.comp.nus.edu.sg

While I start vncserver in step 3 with "vncserver :15". The system prompts that server is already running as: 15 on machine hacchead, but the session isn't displayed in vncserver list
![can't start vncserver](https://github.com/XACCNUS/User-Guide/assets/40317880/a1a5e780-2f10-408b-a488-f2e980110ac6)

**Comment by HongshiTan** [comment]
You need to specify another session rather than :15 and change the ssh port forwarding accordingly.  
Simply run vncserver, and it will auto-select a usable session.

**Comment by bjwtsh** [comment]
@HongshiTan 
Do you mean that the session:15 goes wrong in step3 or just must choose a different session number from the step 0 ?

> You need to specify another session rather than :15 and change the ssh port forwarding accordingly. Simply run vncserver, and it will auto-select a usable session.

**Comment by HongshiTan** [comment]
It does not go wrong,  what it means is that :15 has been occupied by other users.

**Comment by bjwtsh** [comment]
@HongshiTan Thanks for your advice!
I  connected to server successfully with another session number!
