### ISSUE TITLE
U280 devices are not available

### ISSUE THREAD

**Issue by EnXinY** [XACCNUS/Cluster#7]
We are using HACC and we want to use the U280 board for computing, but we found that the devices in 3 of the nodes are in an unavailable state(We use the command "source /opt/xilinx/xrt/setup.sh" to load the environment and use "xbutil examine" to check the status of the board, at this point " Device Ready is No"), and the fourth node is missing the libraries that we want to use, I hope that you can help us to solve this problem, I really appreciate it!

**Comment by EnXinY** [comment]
Or you can help me to install it on U280 node 4: "TAPA (https://tapa.readthedocs.io/en/release/installation.html)", really thanks a lot!

**Comment by HongshiTan** [comment]
Hello, Enxin,

This is an unexpected hardware fault of the u280 board. To address this, we need to perform a cold reboot of the server. However, to minimize disruption to ongoing tasks, we will execute this action only after all users have completed and released their jobs. 

Once the reboot is completed and the U280 boards are back online,  will notify you.

Best

**Comment by EnXinY** [comment]
Thank you very much, this will solve my big problem! :)

**Comment by HongshiTan** [comment]
Hello  EnXin, u280 1,3,4 has been recovered. However,  we are not sure of the fundamental reason causing that. If it happens when you are using them,  please make sure your design is verified in hw emulation and send me the error log.

**Comment by EnXinY** [comment]
Your help is really very much appreciated. I will log issues as I use it and give you feedback.

**Comment by EnXinY** [comment]
I just logged into the node and tried to check the status of the U280, but it still says "Device Ready is NO", is this normal?

**Comment by EnXinY** [comment]
I'm really sorry. But now nodes 1, 2, and 3 still don't seem to work.

![70eda7963aab4c602bd6eeec1b0fe66](https://github.com/XACCNUS/User-Guide/assets/83993463/3a9dd498-90f2-449f-8026-525069b96472)
![6e88283ef437091116f267f3d79f31a](https://github.com/XACCNUS/User-Guide/assets/83993463/b56a50e8-ae06-4336-ac1e-dd76f4fa2fe6)

**Comment by HongshiTan** [comment]
Now should be working. Please let me know if still not.
